version: "3.9"

services:
    rabbit1:
        image: "rabbitmq:3-management"
        hostname: "rabbit"
        environment:
          RABBITMQ_DEFAULT_USER: "Guest"
          RABBITMQ_DEFAULT_PASS: "Guest"
          RABBITMQ_DEFAULT_VHOST: "/"
        ports:
          - "15672:15672"
          - "5672:5672"

    postgres:
        container_name: postgres_container
        image: postgres:11.13
        environment:
          POSTGRES_USER: TestUser
          POSTGRES_PASSWORD: SecuredPassword!123
          POSTGRES_DB: PhoneBookDb
          PGDATA: /data/postgres
          POSTGRES_HOST_AUTH_METHOD: "trust"
        network_mode: host
        #volumes:
        #   - ./postgres:/data/postgres
        ports:
          - "5432:5432"
        restart: unless-stopped
  
    pgadmin:
        container_name: pgadmin_container
        image: dpage/pgadmin4
        environment:
          PGADMIN_DEFAULT_EMAIL: "test@test.com"
          PGADMIN_DEFAULT_PASSWORD: "Guest"
          PGADMIN_CONFIG_SERVER_MODE: 'False'
        #volumes:
        #   - ./pgadmin:/var/lib/pgadmin
        ports:
          - "5050:80"
        restart: unless-stopped